<div class="card overflow-hidden">
    <div class="row g-0">
        <div class="col-md-4">
            <?= Bhtml::img("reportes/1.jpg", "Imagen Reporte", ["width" => "256px"])?>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <!-- Titulo del reporte -->
                <h5 class="card-title" >Reporte Bache #1
                    <!-- Parametros -->
                    <span class="badge bg-light-warning">
                        <i class="ti ti-ruler-2"></i>
                        Diametro: 66cm
                    </span>
                    <span class="badge bg-info">
                        <i class="ti ti-clock"></i>
                        Estado: Pendiente
                    </span>
                    <span class="badge bg-danger">
                        <i class="ti ti-arrow-up-right"></i>
                        Prioridad: Alta
                    </span>
                </h5>
                <p class="card-text">Bache sobre la avenida juarez, cerca del banco santander, retrasa la circulación en el area y puede causar un accidente si no se repara pronto.</p>
                <p class="card-text">
                    <i class="ti ti-user"></i>
                    <small class="text-muted">Juan Pedro Paramo</small>
                    <i class="ti ti-calendar-event"></i>
                    <small class="text-muted">10/13/2025</small>
                    <i class="ti ti-map-pin"></i>
                    <small class="text-muted">Av. Juarez #201</small>
                    <br>
                    <br>
                    <!-- Links -->
                    <a href="#!" class="card-link">Ver Más</a>
                    <a href="#!" class="card-link">Comentarios</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="card overflow-hidden">
    <div class="row g-0">
        <div class="col-md-4">
            <?= Bhtml::img("reportes/2.jpg", "Imagen Reporte", ["width" => "256px"])?>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">Reporte Bache #2 <small class="text-muted">68cm</small></h5>
                <p class="card-text">datos del bache lorem ipsum durun</p>
                <p class="card-text"><small class="text-muted">10/13/2025</small></p>
            </div>
        </div>
    </div>
</div>