<!DOCTYPE html>
<html lang="es">

<head>
    <title><?= (isset($title)) ? $title . ' | ' : '' ?>Sistema de Reportes</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- Favicon icon -->
    <link rel="icon" href="<?= PUBLIC_PATH ?>assets/images/favicon.svg" type="image/x-icon">

    <!-- font css -->
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>assets/fonts/tabler-icons.min.css">
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>assets/fonts/feather.css">
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>assets/fonts/fontawesome.css">
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>assets/fonts/material.css">

    <!-- vendor css -->
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>assets/css/style.css" id="main-style-link">
    <link rel="stylesheet" href="<?= PUBLIC_PATH ?>assets/css/style-preset.css">
</head>

<body data-pc-preset="preset-1" data-pc-sidebar-theme="light" data-pc-sidebar-caption="true" data-pc-direction="ltr"
    data-pc-theme="light">

    <div class="auth-main">
        <div class="auth-wrapper v1">
            <div class="auth-form">
                <?= View::content() ?>
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="<?= PUBLIC_PATH ?>assets/js/plugins/popper.min.js"></script>
    <script src="<?= PUBLIC_PATH ?>assets/js/plugins/simplebar.min.js"></script>
    <script src="<?= PUBLIC_PATH ?>assets/js/plugins/bootstrap.min.js"></script>
    <script src="<?= PUBLIC_PATH ?>assets/js/fonts/custom-font.js"></script>
    <script src="<?= PUBLIC_PATH ?>assets/js/pcoded.js"></script>
    <script src="<?= PUBLIC_PATH ?>assets/js/plugins/feather.min.js"></script>
</body>

</html>