<!DOCTYPE html>
<html lang="es">

<head>
    <title><?= (isset($title)) ? $title . ' | ' : '' ?>Sistema de Reportes</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- Favicon icon -->
    <link rel="icon" href="<?= PUBLIC_PATH ?>storage/icon.png" type="image/x-icon">

    <!-- [Tabler Icons] https://tablericons.com -->
    <link rel="stylesheet" href="/proyecto/libs/mantis/src/assets/fonts/tabler-icons.min.css">
    <!-- [Feather Icons] https://feathericons.com -->
    <link rel="stylesheet" href="/proyecto/libs/mantis/src/assets/fonts/feather.css">
    <!-- [Font Awesome Icons] https://fontawesome.com/icons -->
    <link rel="stylesheet" href="/proyecto/libs/mantis/src/assets/fonts/fontawesome.css">
    <!-- [Material Icons] https://fonts.google.com/icons -->
    <link rel="stylesheet" href="/proyecto/libs/mantis/src/assets/fonts/material.css">
    <!-- [Template CSS Files] -->
    <link rel="stylesheet" href="/proyecto/libs/mantis/dist/assets/css/style.css" id="main-style-link">
    <link rel="stylesheet" href="/proyecto/libs/mantis/dist/assets/css/style-preset.css">
</head>

<body data-pc-preset="preset-1" data-pc-direction="ltr" data-pc-theme="light">

    <div class="auth-main">
        <div class="auth-wrapper">
            <div class="auth-form">
                <?= View::content() ?>
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="/proyecto/libs/mantis/src/assets/js/plugins/popper.min.js"></script>
    <script src="/proyecto/libs/mantis/src/assets/js/plugins/simplebar.min.js"></script>
    <script src="/proyecto/libs/mantis/src/assets/js/plugins/bootstrap.min.js"></script>
    <script src="/proyecto/libs/mantis/src/assets/js/fonts/custom-font.js"></script>
    <script src="/proyecto/libs/mantis/src/assets/js/pcoded.js"></script>
    <script src="/proyecto/libs/mantis/src/assets/js/plugins/feather.min.js"></script>
</body>

</html>