<nav class="pc-sidebar">
    <div class="navbar-wrapper">
        <div class="m-header">
            <a href="" class="b-brand text-primary">
                <!-- ========   Change your logo from here   ============ -->
                <img src="/proyecto/default/public/storage/icon.png" width="40px" alt="logo">
            </a>
        </div>
    <?php View::partial("mantis/sidebar_content") ?>
    </div>
</nav>